### ISSUE TITLE
Database name cannot contain a `.`

### ISSUE THREAD

**Issue by brianwernick** [jeffdcamp/dbtools-gen#15]
- DBTools Gen version: `8.2.0`
 
###### Reproduction Steps
 0. In the `schema.xml` file create a database whose name has a `.` in it. e.g `<database name="test.period"> </database>`
 0. Run `dbtools-gen`

###### Expected Result
The `AppDatabaseConfig` and `DatabaseManager` should correctly convert or exclude the period (e.g.`DatabaseManager.TEST_PERIOD_TABLES_VERSION`)

###### Actual Result
The `AppDatabaseConfig` and `DatabaseManager` include the `.` in the name resulting in an incorrect reference.
e.g. `DatabaseManager.TEST.PERIOD_TABLES_VERSION`

**Comment by jeffdcamp** [comment]
With version 8.2.1 the '.' character, in code, will be replaced with a '_'
